feat(animation): fix the internet by Yves
Mergifyio/www pull request #2
Opened 2021-10-28 21:22 UTC by ErwanSimonetti

As suggested by Sileht, we should have Yves fixing the internet

### Development

- [X] All checks must pass (Semantic Pull Request, pep8, requirements, unit tests, functional tests, security checks, …)
- [X] The code changed/added as part of this pull request must be covered with tests
- [X] Hotfixes must have a link to Sentry issue and the ``hotfix`` label
- [X] Features must have a link to a Linear task

### Code Review

Code review policies are handled and automated by Mergify.

* When all tests pass, reviewers will be assigned automatically.
* When change is approved by at least one review and no pending review are
  remaining, pull request is retested against its base branch.
* The pull request is then merged automatically.

2021-10-29 08:56 UTC, jd approved these changes

2021-10-29 08:57 UTC, jd requested changes

2021-10-29 08:57 UTC, jd commented on homepage-pull-animation/index.html
> +						<span class="a-merg__item__infos">#2137 opened 4 hours ago by Yves</span>
Duplicate!

2021-11-01 15:52 UTC, ErwanSimonetti commented on homepage-pull-animation/index.html
> +						<span class="a-merg__item__infos">#2137 opened 4 hours ago by Yves</span>
You mean I should duplicate these lines somewhere ?

2021-11-01 15:53 UTC, sileht commented on homepage-pull-animation/index.html
> +						<span class="a-merg__item__infos">#2137 opened 4 hours ago by Yves</span>
The pull request number I think

2021-11-01 15:53 UTC, jd commented on homepage-pull-animation/index.html
> +						<span class="a-merg__item__infos">#2137 opened 4 hours ago by Yves</span>
I mean this PR number already exists!

2021-11-01 15:59 UTC, ErwanSimonetti commented on homepage-pull-animation/index.html
> +						<span class="a-merg__item__infos">#2137 opened 4 hours ago by Yves</span>
oh ok, but why is the PR number the same in the whole file ?

2021-11-01 16:39 UTC, jd commented on homepage-pull-animation/index.html
> +						<span class="a-merg__item__infos">#2137 opened 4 hours ago by Yves</span>
You could answer the question yourself. If the file is not what you see online, maybe it's because you're not touching nthe right file? 😂

2021-11-02 08:21 UTC, jd approved these changes

2021-11-02 08:21 UTC, merged